target-version = "py310"


exclude = [
  ".git",
  ".venv",
  "build",
  "dist",
  "migrations",
  "examples/demo",
]


[lint]
extend-select = [
  "B",
  "DJ",
  "E",
  "F",
  "I",
  "RUF",
  "SIM",
  "UP",
  "W",
]
ignore = [
  "B017",
  "B018",
  "B023",
  "B904",
  "B905",
  "DJ001",
  "DJ007",
  "DJ008",
  "E501",
  "F403",
  "RUF012",
  "SIM102",
  "SIM103",
  "SIM105",
  "SIM108",
  "SIM112",
  "SIM117",
  "SIM118",
]


[lint.per-file-ignores]
"**/__init__.py" = ["F401"]
"**/test_*.py" = ["F841"]
